/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ColorModeResponse,
  GetColorsByMode404Response,
  GetColorsByMode422Response,
  LayoutResponse,
} from '../models/index';
import {
    ColorModeResponseFromJSON,
    ColorModeResponseToJSON,
    GetColorsByMode404ResponseFromJSON,
    GetColorsByMode404ResponseToJSON,
    GetColorsByMode422ResponseFromJSON,
    GetColorsByMode422ResponseToJSON,
    LayoutResponseFromJSON,
    LayoutResponseToJSON,
} from '../models/index';

export interface GetColorsByModeRequest {
    mode: GetColorsByModeModeEnum;
}

/**
 * 
 */
export class AppsApi extends runtime.BaseAPI {

    /**
     */
    async getColorsByModeRaw(requestParameters: GetColorsByModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ColorModeResponse>> {
        if (requestParameters['mode'] == null) {
            throw new runtime.RequiredError(
                'mode',
                'Required parameter "mode" was null or undefined when calling getColorsByMode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/colors/{mode}`.replace(`{${"mode"}}`, encodeURIComponent(String(requestParameters['mode']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ColorModeResponseFromJSON(jsonValue));
    }

    /**
     */
    async getColorsByMode(requestParameters: GetColorsByModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ColorModeResponse> {
        const response = await this.getColorsByModeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLayoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LayoutResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/layout/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LayoutResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLayout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LayoutResponse> {
        const response = await this.getLayoutRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetColorsByModeModeEnum = {
    Light: 'light',
    Dark: 'dark'
} as const;
export type GetColorsByModeModeEnum = typeof GetColorsByModeModeEnum[keyof typeof GetColorsByModeModeEnum];
