/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ColorModeResponse,
  ContainerResponse,
  ElementResponse,
  GetColorsByMode404Response,
  GetColorsByMode422Response,
  LayoutResponse,
  MenuResponse,
  PageBySlugResponse,
  PageResponse,
} from '../models/index';
import {
    ColorModeResponseFromJSON,
    ColorModeResponseToJSON,
    ContainerResponseFromJSON,
    ContainerResponseToJSON,
    ElementResponseFromJSON,
    ElementResponseToJSON,
    GetColorsByMode404ResponseFromJSON,
    GetColorsByMode404ResponseToJSON,
    GetColorsByMode422ResponseFromJSON,
    GetColorsByMode422ResponseToJSON,
    LayoutResponseFromJSON,
    LayoutResponseToJSON,
    MenuResponseFromJSON,
    MenuResponseToJSON,
    PageBySlugResponseFromJSON,
    PageBySlugResponseToJSON,
    PageResponseFromJSON,
    PageResponseToJSON,
} from '../models/index';

export interface GetByIdElementRequest {
    elementId: string;
}

export interface GetColorsByModeRequest {
    mode: GetColorsByModeModeEnum;
}

export interface GetContainerbyidRequest {
    containerId: string;
}

export interface GetPageByIdRequest {
    pageId: string;
}

export interface GetPageBySlugRequest {
    slug: string;
}

/**
 * 
 */
export class AppsApi extends runtime.BaseAPI {

    /**
     */
    async getByIdElementRaw(requestParameters: GetByIdElementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ElementResponse>> {
        if (requestParameters['elementId'] == null) {
            throw new runtime.RequiredError(
                'elementId',
                'Required parameter "elementId" was null or undefined when calling getByIdElement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/element/{elementId}`.replace(`{${"elementId"}}`, encodeURIComponent(String(requestParameters['elementId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ElementResponseFromJSON(jsonValue));
    }

    /**
     */
    async getByIdElement(requestParameters: GetByIdElementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ElementResponse> {
        const response = await this.getByIdElementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getColorsByModeRaw(requestParameters: GetColorsByModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ColorModeResponse>> {
        if (requestParameters['mode'] == null) {
            throw new runtime.RequiredError(
                'mode',
                'Required parameter "mode" was null or undefined when calling getColorsByMode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/colors/{mode}`.replace(`{${"mode"}}`, encodeURIComponent(String(requestParameters['mode']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ColorModeResponseFromJSON(jsonValue));
    }

    /**
     */
    async getColorsByMode(requestParameters: GetColorsByModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ColorModeResponse> {
        const response = await this.getColorsByModeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getContainerRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/container`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerResponseFromJSON(jsonValue));
    }

    /**
     */
    async getContainer(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerResponse> {
        const response = await this.getContainerRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getContainerbyidRaw(requestParameters: GetContainerbyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ContainerResponse>> {
        if (requestParameters['containerId'] == null) {
            throw new runtime.RequiredError(
                'containerId',
                'Required parameter "containerId" was null or undefined when calling getContainerbyid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/container/{containerId}`.replace(`{${"containerId"}}`, encodeURIComponent(String(requestParameters['containerId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ContainerResponseFromJSON(jsonValue));
    }

    /**
     */
    async getContainerbyid(requestParameters: GetContainerbyidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ContainerResponse> {
        const response = await this.getContainerbyidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getElementRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ElementResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/element`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ElementResponseFromJSON(jsonValue));
    }

    /**
     */
    async getElement(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ElementResponse> {
        const response = await this.getElementRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getLayoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LayoutResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/layout`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LayoutResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLayout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LayoutResponse> {
        const response = await this.getLayoutRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMenuRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MenuResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/menu`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MenuResponseFromJSON(jsonValue));
    }

    /**
     */
    async getMenu(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MenuResponse> {
        const response = await this.getMenuRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getPageRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getPage(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageResponse> {
        const response = await this.getPageRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getPageByIdRaw(requestParameters: GetPageByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageResponse>> {
        if (requestParameters['pageId'] == null) {
            throw new runtime.RequiredError(
                'pageId',
                'Required parameter "pageId" was null or undefined when calling getPageById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/page/{pageId}`.replace(`{${"pageId"}}`, encodeURIComponent(String(requestParameters['pageId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageResponseFromJSON(jsonValue));
    }

    /**
     */
    async getPageById(requestParameters: GetPageByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageResponse> {
        const response = await this.getPageByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPageBySlugRaw(requestParameters: GetPageBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageBySlugResponse>> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getPageBySlug().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-AppSecret"] = await this.configuration.apiKey("X-Nexa-AppSecret"); // AppSecretAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Nexa-Appid"] = await this.configuration.apiKey("X-Nexa-Appid"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/apps/page/slug/{slug}`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageBySlugResponseFromJSON(jsonValue));
    }

    /**
     */
    async getPageBySlug(requestParameters: GetPageBySlugRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageBySlugResponse> {
        const response = await this.getPageBySlugRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetColorsByModeModeEnum = {
    Light: 'light',
    Dark: 'dark'
} as const;
export type GetColorsByModeModeEnum = typeof GetColorsByModeModeEnum[keyof typeof GetColorsByModeModeEnum];
