/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColorModeResponseThemePaletteBackground
 */
export interface ColorModeResponseThemePaletteBackground {
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteBackground
     */
    _default?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteBackground
     */
    paper?: string;
}

/**
 * Check if a given object implements the ColorModeResponseThemePaletteBackground interface.
 */
export function instanceOfColorModeResponseThemePaletteBackground(value: object): value is ColorModeResponseThemePaletteBackground {
    return true;
}

export function ColorModeResponseThemePaletteBackgroundFromJSON(json: any): ColorModeResponseThemePaletteBackground {
    return ColorModeResponseThemePaletteBackgroundFromJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteBackgroundFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorModeResponseThemePaletteBackground {
    if (json == null) {
        return json;
    }
    return {
        
        '_default': json['default'] == null ? undefined : json['default'],
        'paper': json['paper'] == null ? undefined : json['paper'],
    };
}

export function ColorModeResponseThemePaletteBackgroundToJSON(json: any): ColorModeResponseThemePaletteBackground {
    return ColorModeResponseThemePaletteBackgroundToJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteBackgroundToJSONTyped(value?: ColorModeResponseThemePaletteBackground | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default': value['_default'],
        'paper': value['paper'],
    };
}

