/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColorModeResponseTheme } from './ColorModeResponseTheme';
import {
    ColorModeResponseThemeFromJSON,
    ColorModeResponseThemeFromJSONTyped,
    ColorModeResponseThemeToJSON,
    ColorModeResponseThemeToJSONTyped,
} from './ColorModeResponseTheme';

/**
 * 
 * @export
 * @interface ColorModeResponse
 */
export interface ColorModeResponse {
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponse
     */
    mode: string;
    /**
     * 
     * @type {ColorModeResponseTheme}
     * @memberof ColorModeResponse
     */
    theme: ColorModeResponseTheme;
}

/**
 * Check if a given object implements the ColorModeResponse interface.
 */
export function instanceOfColorModeResponse(value: object): value is ColorModeResponse {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('theme' in value) || value['theme'] === undefined) return false;
    return true;
}

export function ColorModeResponseFromJSON(json: any): ColorModeResponse {
    return ColorModeResponseFromJSONTyped(json, false);
}

export function ColorModeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorModeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'theme': ColorModeResponseThemeFromJSON(json['theme']),
    };
}

export function ColorModeResponseToJSON(json: any): ColorModeResponse {
    return ColorModeResponseToJSONTyped(json, false);
}

export function ColorModeResponseToJSONTyped(value?: ColorModeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'theme': ColorModeResponseThemeToJSON(value['theme']),
    };
}

