/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColorModeResponseThemePalettePrimary
 */
export interface ColorModeResponseThemePalettePrimary {
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePalettePrimary
     */
    light?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePalettePrimary
     */
    main: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePalettePrimary
     */
    dark?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePalettePrimary
     */
    contrastText?: string;
}

/**
 * Check if a given object implements the ColorModeResponseThemePalettePrimary interface.
 */
export function instanceOfColorModeResponseThemePalettePrimary(value: object): value is ColorModeResponseThemePalettePrimary {
    if (!('main' in value) || value['main'] === undefined) return false;
    return true;
}

export function ColorModeResponseThemePalettePrimaryFromJSON(json: any): ColorModeResponseThemePalettePrimary {
    return ColorModeResponseThemePalettePrimaryFromJSONTyped(json, false);
}

export function ColorModeResponseThemePalettePrimaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorModeResponseThemePalettePrimary {
    if (json == null) {
        return json;
    }
    return {
        
        'light': json['light'] == null ? undefined : json['light'],
        'main': json['main'],
        'dark': json['dark'] == null ? undefined : json['dark'],
        'contrastText': json['contrastText'] == null ? undefined : json['contrastText'],
    };
}

export function ColorModeResponseThemePalettePrimaryToJSON(json: any): ColorModeResponseThemePalettePrimary {
    return ColorModeResponseThemePalettePrimaryToJSONTyped(json, false);
}

export function ColorModeResponseThemePalettePrimaryToJSONTyped(value?: ColorModeResponseThemePalettePrimary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'light': value['light'],
        'main': value['main'],
        'dark': value['dark'],
        'contrastText': value['contrastText'],
    };
}

