/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColorModeResponseThemePaletteAction
 */
export interface ColorModeResponseThemePaletteAction {
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteAction
     */
    active?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteAction
     */
    hover?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteAction
     */
    selected?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteAction
     */
    disabled?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteAction
     */
    disabledBackground?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteAction
     */
    focus?: string;
}

/**
 * Check if a given object implements the ColorModeResponseThemePaletteAction interface.
 */
export function instanceOfColorModeResponseThemePaletteAction(value: object): value is ColorModeResponseThemePaletteAction {
    return true;
}

export function ColorModeResponseThemePaletteActionFromJSON(json: any): ColorModeResponseThemePaletteAction {
    return ColorModeResponseThemePaletteActionFromJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorModeResponseThemePaletteAction {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'hover': json['hover'] == null ? undefined : json['hover'],
        'selected': json['selected'] == null ? undefined : json['selected'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'disabledBackground': json['disabledBackground'] == null ? undefined : json['disabledBackground'],
        'focus': json['focus'] == null ? undefined : json['focus'],
    };
}

export function ColorModeResponseThemePaletteActionToJSON(json: any): ColorModeResponseThemePaletteAction {
    return ColorModeResponseThemePaletteActionToJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteActionToJSONTyped(value?: ColorModeResponseThemePaletteAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'hover': value['hover'],
        'selected': value['selected'],
        'disabled': value['disabled'],
        'disabledBackground': value['disabledBackground'],
        'focus': value['focus'],
    };
}

