/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColorModeResponseThemePalette } from './ColorModeResponseThemePalette';
import {
    ColorModeResponseThemePaletteFromJSON,
    ColorModeResponseThemePaletteFromJSONTyped,
    ColorModeResponseThemePaletteToJSON,
    ColorModeResponseThemePaletteToJSONTyped,
} from './ColorModeResponseThemePalette';

/**
 * 
 * @export
 * @interface ColorModeResponseTheme
 */
export interface ColorModeResponseTheme {
    /**
     * 
     * @type {ColorModeResponseThemePalette}
     * @memberof ColorModeResponseTheme
     */
    palette: ColorModeResponseThemePalette;
}

/**
 * Check if a given object implements the ColorModeResponseTheme interface.
 */
export function instanceOfColorModeResponseTheme(value: object): value is ColorModeResponseTheme {
    if (!('palette' in value) || value['palette'] === undefined) return false;
    return true;
}

export function ColorModeResponseThemeFromJSON(json: any): ColorModeResponseTheme {
    return ColorModeResponseThemeFromJSONTyped(json, false);
}

export function ColorModeResponseThemeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorModeResponseTheme {
    if (json == null) {
        return json;
    }
    return {
        
        'palette': ColorModeResponseThemePaletteFromJSON(json['palette']),
    };
}

export function ColorModeResponseThemeToJSON(json: any): ColorModeResponseTheme {
    return ColorModeResponseThemeToJSONTyped(json, false);
}

export function ColorModeResponseThemeToJSONTyped(value?: ColorModeResponseTheme | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'palette': ColorModeResponseThemePaletteToJSON(value['palette']),
    };
}

