/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColorModeResponseThemePaletteText
 */
export interface ColorModeResponseThemePaletteText {
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteText
     */
    primary?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteText
     */
    secondary?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePaletteText
     */
    disabled?: string;
}

/**
 * Check if a given object implements the ColorModeResponseThemePaletteText interface.
 */
export function instanceOfColorModeResponseThemePaletteText(value: object): value is ColorModeResponseThemePaletteText {
    return true;
}

export function ColorModeResponseThemePaletteTextFromJSON(json: any): ColorModeResponseThemePaletteText {
    return ColorModeResponseThemePaletteTextFromJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorModeResponseThemePaletteText {
    if (json == null) {
        return json;
    }
    return {
        
        'primary': json['primary'] == null ? undefined : json['primary'],
        'secondary': json['secondary'] == null ? undefined : json['secondary'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
    };
}

export function ColorModeResponseThemePaletteTextToJSON(json: any): ColorModeResponseThemePaletteText {
    return ColorModeResponseThemePaletteTextToJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteTextToJSONTyped(value?: ColorModeResponseThemePaletteText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primary': value['primary'],
        'secondary': value['secondary'],
        'disabled': value['disabled'],
    };
}

