/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColorModeResponseThemePaletteBackground } from './ColorModeResponseThemePaletteBackground';
import {
    ColorModeResponseThemePaletteBackgroundFromJSON,
    ColorModeResponseThemePaletteBackgroundFromJSONTyped,
    ColorModeResponseThemePaletteBackgroundToJSON,
    ColorModeResponseThemePaletteBackgroundToJSONTyped,
} from './ColorModeResponseThemePaletteBackground';
import type { ColorModeResponseThemePaletteAction } from './ColorModeResponseThemePaletteAction';
import {
    ColorModeResponseThemePaletteActionFromJSON,
    ColorModeResponseThemePaletteActionFromJSONTyped,
    ColorModeResponseThemePaletteActionToJSON,
    ColorModeResponseThemePaletteActionToJSONTyped,
} from './ColorModeResponseThemePaletteAction';
import type { ColorModeResponseThemePaletteText } from './ColorModeResponseThemePaletteText';
import {
    ColorModeResponseThemePaletteTextFromJSON,
    ColorModeResponseThemePaletteTextFromJSONTyped,
    ColorModeResponseThemePaletteTextToJSON,
    ColorModeResponseThemePaletteTextToJSONTyped,
} from './ColorModeResponseThemePaletteText';
import type { ColorModeResponseThemePalettePrimary } from './ColorModeResponseThemePalettePrimary';
import {
    ColorModeResponseThemePalettePrimaryFromJSON,
    ColorModeResponseThemePalettePrimaryFromJSONTyped,
    ColorModeResponseThemePalettePrimaryToJSON,
    ColorModeResponseThemePalettePrimaryToJSONTyped,
} from './ColorModeResponseThemePalettePrimary';

/**
 * 
 * @export
 * @interface ColorModeResponseThemePalette
 */
export interface ColorModeResponseThemePalette {
    /**
     * 
     * @type {ColorModeResponseThemePalettePrimary}
     * @memberof ColorModeResponseThemePalette
     */
    primary: ColorModeResponseThemePalettePrimary;
    /**
     * 
     * @type {ColorModeResponseThemePalettePrimary}
     * @memberof ColorModeResponseThemePalette
     */
    secondary: ColorModeResponseThemePalettePrimary;
    /**
     * 
     * @type {ColorModeResponseThemePalettePrimary}
     * @memberof ColorModeResponseThemePalette
     */
    error?: ColorModeResponseThemePalettePrimary;
    /**
     * 
     * @type {ColorModeResponseThemePalettePrimary}
     * @memberof ColorModeResponseThemePalette
     */
    warning?: ColorModeResponseThemePalettePrimary;
    /**
     * 
     * @type {ColorModeResponseThemePalettePrimary}
     * @memberof ColorModeResponseThemePalette
     */
    info?: ColorModeResponseThemePalettePrimary;
    /**
     * 
     * @type {ColorModeResponseThemePalettePrimary}
     * @memberof ColorModeResponseThemePalette
     */
    success?: ColorModeResponseThemePalettePrimary;
    /**
     * 
     * @type {ColorModeResponseThemePaletteText}
     * @memberof ColorModeResponseThemePalette
     */
    text?: ColorModeResponseThemePaletteText;
    /**
     * 
     * @type {ColorModeResponseThemePaletteBackground}
     * @memberof ColorModeResponseThemePalette
     */
    background?: ColorModeResponseThemePaletteBackground;
    /**
     * 
     * @type {ColorModeResponseThemePaletteAction}
     * @memberof ColorModeResponseThemePalette
     */
    action?: ColorModeResponseThemePaletteAction;
    /**
     * 
     * @type {string}
     * @memberof ColorModeResponseThemePalette
     */
    divider?: string;
}

/**
 * Check if a given object implements the ColorModeResponseThemePalette interface.
 */
export function instanceOfColorModeResponseThemePalette(value: object): value is ColorModeResponseThemePalette {
    if (!('primary' in value) || value['primary'] === undefined) return false;
    if (!('secondary' in value) || value['secondary'] === undefined) return false;
    return true;
}

export function ColorModeResponseThemePaletteFromJSON(json: any): ColorModeResponseThemePalette {
    return ColorModeResponseThemePaletteFromJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorModeResponseThemePalette {
    if (json == null) {
        return json;
    }
    return {
        
        'primary': ColorModeResponseThemePalettePrimaryFromJSON(json['primary']),
        'secondary': ColorModeResponseThemePalettePrimaryFromJSON(json['secondary']),
        'error': json['error'] == null ? undefined : ColorModeResponseThemePalettePrimaryFromJSON(json['error']),
        'warning': json['warning'] == null ? undefined : ColorModeResponseThemePalettePrimaryFromJSON(json['warning']),
        'info': json['info'] == null ? undefined : ColorModeResponseThemePalettePrimaryFromJSON(json['info']),
        'success': json['success'] == null ? undefined : ColorModeResponseThemePalettePrimaryFromJSON(json['success']),
        'text': json['text'] == null ? undefined : ColorModeResponseThemePaletteTextFromJSON(json['text']),
        'background': json['background'] == null ? undefined : ColorModeResponseThemePaletteBackgroundFromJSON(json['background']),
        'action': json['action'] == null ? undefined : ColorModeResponseThemePaletteActionFromJSON(json['action']),
        'divider': json['divider'] == null ? undefined : json['divider'],
    };
}

export function ColorModeResponseThemePaletteToJSON(json: any): ColorModeResponseThemePalette {
    return ColorModeResponseThemePaletteToJSONTyped(json, false);
}

export function ColorModeResponseThemePaletteToJSONTyped(value?: ColorModeResponseThemePalette | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primary': ColorModeResponseThemePalettePrimaryToJSON(value['primary']),
        'secondary': ColorModeResponseThemePalettePrimaryToJSON(value['secondary']),
        'error': ColorModeResponseThemePalettePrimaryToJSON(value['error']),
        'warning': ColorModeResponseThemePalettePrimaryToJSON(value['warning']),
        'info': ColorModeResponseThemePalettePrimaryToJSON(value['info']),
        'success': ColorModeResponseThemePalettePrimaryToJSON(value['success']),
        'text': ColorModeResponseThemePaletteTextToJSON(value['text']),
        'background': ColorModeResponseThemePaletteBackgroundToJSON(value['background']),
        'action': ColorModeResponseThemePaletteActionToJSON(value['action']),
        'divider': value['divider'],
    };
}

