/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerResponseItemsInner
 */
export interface ContainerResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseItemsInner
     */
    element?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseItemsInner
     */
    id?: string;
}

/**
 * Check if a given object implements the ContainerResponseItemsInner interface.
 */
export function instanceOfContainerResponseItemsInner(value: object): value is ContainerResponseItemsInner {
    return true;
}

export function ContainerResponseItemsInnerFromJSON(json: any): ContainerResponseItemsInner {
    return ContainerResponseItemsInnerFromJSONTyped(json, false);
}

export function ContainerResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'element': json['element'] == null ? undefined : json['element'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function ContainerResponseItemsInnerToJSON(json: any): ContainerResponseItemsInner {
    return ContainerResponseItemsInnerToJSONTyped(json, false);
}

export function ContainerResponseItemsInnerToJSONTyped(value?: ContainerResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'element': value['element'],
        '_id': value['id'],
    };
}

