/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerResponseLayoutOptionsGridOptionsDefaultSize } from './ContainerResponseLayoutOptionsGridOptionsDefaultSize';
import {
    ContainerResponseLayoutOptionsGridOptionsDefaultSizeFromJSON,
    ContainerResponseLayoutOptionsGridOptionsDefaultSizeFromJSONTyped,
    ContainerResponseLayoutOptionsGridOptionsDefaultSizeToJSON,
    ContainerResponseLayoutOptionsGridOptionsDefaultSizeToJSONTyped,
} from './ContainerResponseLayoutOptionsGridOptionsDefaultSize';
import type { ContainerResponseLayoutOptionsGridOptionsSizeDataInner } from './ContainerResponseLayoutOptionsGridOptionsSizeDataInner';
import {
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerFromJSON,
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerFromJSONTyped,
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerToJSON,
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerToJSONTyped,
} from './ContainerResponseLayoutOptionsGridOptionsSizeDataInner';

/**
 * 
 * @export
 * @interface ContainerResponseLayoutOptionsGridOptions
 */
export interface ContainerResponseLayoutOptionsGridOptions {
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    spacing?: number;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    direction?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    justifyContent?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    alignItems?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    wrap?: string;
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    columns: number;
    /**
     * 
     * @type {Array<ContainerResponseLayoutOptionsGridOptionsSizeDataInner>}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    sizeData?: Array<ContainerResponseLayoutOptionsGridOptionsSizeDataInner>;
    /**
     * 
     * @type {ContainerResponseLayoutOptionsGridOptionsDefaultSize}
     * @memberof ContainerResponseLayoutOptionsGridOptions
     */
    defaultSize: ContainerResponseLayoutOptionsGridOptionsDefaultSize;
}

/**
 * Check if a given object implements the ContainerResponseLayoutOptionsGridOptions interface.
 */
export function instanceOfContainerResponseLayoutOptionsGridOptions(value: object): value is ContainerResponseLayoutOptionsGridOptions {
    if (!('columns' in value) || value['columns'] === undefined) return false;
    if (!('defaultSize' in value) || value['defaultSize'] === undefined) return false;
    return true;
}

export function ContainerResponseLayoutOptionsGridOptionsFromJSON(json: any): ContainerResponseLayoutOptionsGridOptions {
    return ContainerResponseLayoutOptionsGridOptionsFromJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsGridOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseLayoutOptionsGridOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'spacing': json['spacing'] == null ? undefined : json['spacing'],
        'direction': json['direction'] == null ? undefined : json['direction'],
        'justifyContent': json['justifyContent'] == null ? undefined : json['justifyContent'],
        'alignItems': json['alignItems'] == null ? undefined : json['alignItems'],
        'wrap': json['wrap'] == null ? undefined : json['wrap'],
        'columns': json['columns'],
        'sizeData': json['sizeData'] == null ? undefined : ((json['sizeData'] as Array<any>).map(ContainerResponseLayoutOptionsGridOptionsSizeDataInnerFromJSON)),
        'defaultSize': ContainerResponseLayoutOptionsGridOptionsDefaultSizeFromJSON(json['defaultSize']),
    };
}

export function ContainerResponseLayoutOptionsGridOptionsToJSON(json: any): ContainerResponseLayoutOptionsGridOptions {
    return ContainerResponseLayoutOptionsGridOptionsToJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsGridOptionsToJSONTyped(value?: ContainerResponseLayoutOptionsGridOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spacing': value['spacing'],
        'direction': value['direction'],
        'justifyContent': value['justifyContent'],
        'alignItems': value['alignItems'],
        'wrap': value['wrap'],
        'columns': value['columns'],
        'sizeData': value['sizeData'] == null ? undefined : ((value['sizeData'] as Array<any>).map(ContainerResponseLayoutOptionsGridOptionsSizeDataInnerToJSON)),
        'defaultSize': ContainerResponseLayoutOptionsGridOptionsDefaultSizeToJSON(value['defaultSize']),
    };
}

