/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerResponseLayoutOptionsStackOptions
 */
export interface ContainerResponseLayoutOptionsStackOptions {
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsStackOptions
     */
    spacing?: number;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsStackOptions
     */
    direction?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsStackOptions
     */
    justifyContent?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsStackOptions
     */
    alignItems?: string;
    /**
     * 
     * @type {any}
     * @memberof ContainerResponseLayoutOptionsStackOptions
     */
    divider?: any | null;
}

/**
 * Check if a given object implements the ContainerResponseLayoutOptionsStackOptions interface.
 */
export function instanceOfContainerResponseLayoutOptionsStackOptions(value: object): value is ContainerResponseLayoutOptionsStackOptions {
    return true;
}

export function ContainerResponseLayoutOptionsStackOptionsFromJSON(json: any): ContainerResponseLayoutOptionsStackOptions {
    return ContainerResponseLayoutOptionsStackOptionsFromJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsStackOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseLayoutOptionsStackOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'spacing': json['spacing'] == null ? undefined : json['spacing'],
        'direction': json['direction'] == null ? undefined : json['direction'],
        'justifyContent': json['justifyContent'] == null ? undefined : json['justifyContent'],
        'alignItems': json['alignItems'] == null ? undefined : json['alignItems'],
        'divider': json['divider'] == null ? undefined : json['divider'],
    };
}

export function ContainerResponseLayoutOptionsStackOptionsToJSON(json: any): ContainerResponseLayoutOptionsStackOptions {
    return ContainerResponseLayoutOptionsStackOptionsToJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsStackOptionsToJSONTyped(value?: ContainerResponseLayoutOptionsStackOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spacing': value['spacing'],
        'direction': value['direction'],
        'justifyContent': value['justifyContent'],
        'alignItems': value['alignItems'],
        'divider': value['divider'],
    };
}

