/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerResponseStyle
 */
export interface ContainerResponseStyle {
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    backgroundColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    textColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    textMutedColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    headerFontFamily?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    textFontFamily?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    headerFontSize?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    textFontSize?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    borderRadius?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    padding?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseStyle
     */
    customCSS?: string;
}

/**
 * Check if a given object implements the ContainerResponseStyle interface.
 */
export function instanceOfContainerResponseStyle(value: object): value is ContainerResponseStyle {
    return true;
}

export function ContainerResponseStyleFromJSON(json: any): ContainerResponseStyle {
    return ContainerResponseStyleFromJSONTyped(json, false);
}

export function ContainerResponseStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseStyle {
    if (json == null) {
        return json;
    }
    return {
        
        'backgroundColor': json['backgroundColor'] == null ? undefined : json['backgroundColor'],
        'textColor': json['textColor'] == null ? undefined : json['textColor'],
        'textMutedColor': json['textMutedColor'] == null ? undefined : json['textMutedColor'],
        'headerFontFamily': json['headerFontFamily'] == null ? undefined : json['headerFontFamily'],
        'textFontFamily': json['textFontFamily'] == null ? undefined : json['textFontFamily'],
        'headerFontSize': json['headerFontSize'] == null ? undefined : json['headerFontSize'],
        'textFontSize': json['textFontSize'] == null ? undefined : json['textFontSize'],
        'borderRadius': json['borderRadius'] == null ? undefined : json['borderRadius'],
        'padding': json['padding'] == null ? undefined : json['padding'],
        'customCSS': json['customCSS'] == null ? undefined : json['customCSS'],
    };
}

export function ContainerResponseStyleToJSON(json: any): ContainerResponseStyle {
    return ContainerResponseStyleToJSONTyped(json, false);
}

export function ContainerResponseStyleToJSONTyped(value?: ContainerResponseStyle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backgroundColor': value['backgroundColor'],
        'textColor': value['textColor'],
        'textMutedColor': value['textMutedColor'],
        'headerFontFamily': value['headerFontFamily'],
        'textFontFamily': value['textFontFamily'],
        'headerFontSize': value['headerFontSize'],
        'textFontSize': value['textFontSize'],
        'borderRadius': value['borderRadius'],
        'padding': value['padding'],
        'customCSS': value['customCSS'],
    };
}

