/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerResponseLayoutOptionsTabOptions
 */
export interface ContainerResponseLayoutOptionsTabOptions {
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsTabOptions
     */
    orientation?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsTabOptions
     */
    variant?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContainerResponseLayoutOptionsTabOptions
     */
    centered?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsTabOptions
     */
    indicatorColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsTabOptions
     */
    textColor?: string;
}

/**
 * Check if a given object implements the ContainerResponseLayoutOptionsTabOptions interface.
 */
export function instanceOfContainerResponseLayoutOptionsTabOptions(value: object): value is ContainerResponseLayoutOptionsTabOptions {
    return true;
}

export function ContainerResponseLayoutOptionsTabOptionsFromJSON(json: any): ContainerResponseLayoutOptionsTabOptions {
    return ContainerResponseLayoutOptionsTabOptionsFromJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsTabOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseLayoutOptionsTabOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'orientation': json['orientation'] == null ? undefined : json['orientation'],
        'variant': json['variant'] == null ? undefined : json['variant'],
        'centered': json['centered'] == null ? undefined : json['centered'],
        'indicatorColor': json['indicatorColor'] == null ? undefined : json['indicatorColor'],
        'textColor': json['textColor'] == null ? undefined : json['textColor'],
    };
}

export function ContainerResponseLayoutOptionsTabOptionsToJSON(json: any): ContainerResponseLayoutOptionsTabOptions {
    return ContainerResponseLayoutOptionsTabOptionsToJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsTabOptionsToJSONTyped(value?: ContainerResponseLayoutOptionsTabOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orientation': value['orientation'],
        'variant': value['variant'],
        'centered': value['centered'],
        'indicatorColor': value['indicatorColor'],
        'textColor': value['textColor'],
    };
}

