/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseAvailableInner } from './PageResponseAvailableInner';
import {
    PageResponseAvailableInnerFromJSON,
    PageResponseAvailableInnerFromJSONTyped,
    PageResponseAvailableInnerToJSON,
    PageResponseAvailableInnerToJSONTyped,
} from './PageResponseAvailableInner';
import type { ContainerResponseItemsInner } from './ContainerResponseItemsInner';
import {
    ContainerResponseItemsInnerFromJSON,
    ContainerResponseItemsInnerFromJSONTyped,
    ContainerResponseItemsInnerToJSON,
    ContainerResponseItemsInnerToJSONTyped,
} from './ContainerResponseItemsInner';
import type { ContainerResponseLayoutOptions } from './ContainerResponseLayoutOptions';
import {
    ContainerResponseLayoutOptionsFromJSON,
    ContainerResponseLayoutOptionsFromJSONTyped,
    ContainerResponseLayoutOptionsToJSON,
    ContainerResponseLayoutOptionsToJSONTyped,
} from './ContainerResponseLayoutOptions';
import type { ContainerResponseStyle } from './ContainerResponseStyle';
import {
    ContainerResponseStyleFromJSON,
    ContainerResponseStyleFromJSONTyped,
    ContainerResponseStyleToJSON,
    ContainerResponseStyleToJSONTyped,
} from './ContainerResponseStyle';

/**
 * 
 * @export
 * @interface ContainerResponse
 */
export interface ContainerResponse {
    /**
     * 
     * @type {string}
     * @memberof ContainerResponse
     */
    referenceName: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponse
     */
    description: string;
    /**
     * 
     * @type {ContainerResponseLayoutOptions}
     * @memberof ContainerResponse
     */
    layoutOptions: ContainerResponseLayoutOptions;
    /**
     * 
     * @type {Array<ContainerResponseItemsInner>}
     * @memberof ContainerResponse
     */
    items?: Array<ContainerResponseItemsInner>;
    /**
     * 
     * @type {ContainerResponseStyle}
     * @memberof ContainerResponse
     */
    style?: ContainerResponseStyle;
    /**
     * 
     * @type {Array<PageResponseAvailableInner>}
     * @memberof ContainerResponse
     */
    available?: Array<PageResponseAvailableInner>;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponse
     */
    updatedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContainerResponse
     */
    draft?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContainerResponse
     */
    publish?: boolean;
}

/**
 * Check if a given object implements the ContainerResponse interface.
 */
export function instanceOfContainerResponse(value: object): value is ContainerResponse {
    if (!('referenceName' in value) || value['referenceName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('layoutOptions' in value) || value['layoutOptions'] === undefined) return false;
    return true;
}

export function ContainerResponseFromJSON(json: any): ContainerResponse {
    return ContainerResponseFromJSONTyped(json, false);
}

export function ContainerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'referenceName': json['referenceName'],
        'description': json['description'],
        'layoutOptions': ContainerResponseLayoutOptionsFromJSON(json['layoutOptions']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ContainerResponseItemsInnerFromJSON)),
        'style': json['style'] == null ? undefined : ContainerResponseStyleFromJSON(json['style']),
        'available': json['available'] == null ? undefined : ((json['available'] as Array<any>).map(PageResponseAvailableInnerFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'draft': json['draft'] == null ? undefined : json['draft'],
        'publish': json['publish'] == null ? undefined : json['publish'],
    };
}

export function ContainerResponseToJSON(json: any): ContainerResponse {
    return ContainerResponseToJSONTyped(json, false);
}

export function ContainerResponseToJSONTyped(value?: ContainerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referenceName': value['referenceName'],
        'description': value['description'],
        'layoutOptions': ContainerResponseLayoutOptionsToJSON(value['layoutOptions']),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ContainerResponseItemsInnerToJSON)),
        'style': ContainerResponseStyleToJSON(value['style']),
        'available': value['available'] == null ? undefined : ((value['available'] as Array<any>).map(PageResponseAvailableInnerToJSON)),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'draft': value['draft'],
        'publish': value['publish'],
    };
}

