/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSize } from './ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSize';
import {
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSizeFromJSON,
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSizeFromJSONTyped,
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSizeToJSON,
    ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSizeToJSONTyped,
} from './ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSize';

/**
 * 
 * @export
 * @interface ContainerResponseLayoutOptionsGridOptionsSizeDataInner
 */
export interface ContainerResponseLayoutOptionsGridOptionsSizeDataInner {
    /**
     * 
     * @type {any}
     * @memberof ContainerResponseLayoutOptionsGridOptionsSizeDataInner
     */
    column?: any | null;
    /**
     * 
     * @type {ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSize}
     * @memberof ContainerResponseLayoutOptionsGridOptionsSizeDataInner
     */
    size: ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSize;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsGridOptionsSizeDataInner
     */
    id?: string;
}

/**
 * Check if a given object implements the ContainerResponseLayoutOptionsGridOptionsSizeDataInner interface.
 */
export function instanceOfContainerResponseLayoutOptionsGridOptionsSizeDataInner(value: object): value is ContainerResponseLayoutOptionsGridOptionsSizeDataInner {
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function ContainerResponseLayoutOptionsGridOptionsSizeDataInnerFromJSON(json: any): ContainerResponseLayoutOptionsGridOptionsSizeDataInner {
    return ContainerResponseLayoutOptionsGridOptionsSizeDataInnerFromJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsGridOptionsSizeDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseLayoutOptionsGridOptionsSizeDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'] == null ? undefined : json['column'],
        'size': ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSizeFromJSON(json['size']),
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function ContainerResponseLayoutOptionsGridOptionsSizeDataInnerToJSON(json: any): ContainerResponseLayoutOptionsGridOptionsSizeDataInner {
    return ContainerResponseLayoutOptionsGridOptionsSizeDataInnerToJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsGridOptionsSizeDataInnerToJSONTyped(value?: ContainerResponseLayoutOptionsGridOptionsSizeDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': value['column'],
        'size': ContainerResponseLayoutOptionsGridOptionsSizeDataInnerSizeToJSON(value['size']),
        '_id': value['id'],
    };
}

