/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerResponseLayoutOptionsFluidOptions
 */
export interface ContainerResponseLayoutOptionsFluidOptions {
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsFluidOptions
     */
    gutter?: number;
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptionsFluidOptions
     */
    justify?: string;
}

/**
 * Check if a given object implements the ContainerResponseLayoutOptionsFluidOptions interface.
 */
export function instanceOfContainerResponseLayoutOptionsFluidOptions(value: object): value is ContainerResponseLayoutOptionsFluidOptions {
    return true;
}

export function ContainerResponseLayoutOptionsFluidOptionsFromJSON(json: any): ContainerResponseLayoutOptionsFluidOptions {
    return ContainerResponseLayoutOptionsFluidOptionsFromJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsFluidOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseLayoutOptionsFluidOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'gutter': json['gutter'] == null ? undefined : json['gutter'],
        'justify': json['justify'] == null ? undefined : json['justify'],
    };
}

export function ContainerResponseLayoutOptionsFluidOptionsToJSON(json: any): ContainerResponseLayoutOptionsFluidOptions {
    return ContainerResponseLayoutOptionsFluidOptionsToJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsFluidOptionsToJSONTyped(value?: ContainerResponseLayoutOptionsFluidOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gutter': value['gutter'],
        'justify': value['justify'],
    };
}

