/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContainerResponseLayoutOptionsGridOptions } from './ContainerResponseLayoutOptionsGridOptions';
import {
    ContainerResponseLayoutOptionsGridOptionsFromJSON,
    ContainerResponseLayoutOptionsGridOptionsFromJSONTyped,
    ContainerResponseLayoutOptionsGridOptionsToJSON,
    ContainerResponseLayoutOptionsGridOptionsToJSONTyped,
} from './ContainerResponseLayoutOptionsGridOptions';
import type { ContainerResponseLayoutOptionsStackOptions } from './ContainerResponseLayoutOptionsStackOptions';
import {
    ContainerResponseLayoutOptionsStackOptionsFromJSON,
    ContainerResponseLayoutOptionsStackOptionsFromJSONTyped,
    ContainerResponseLayoutOptionsStackOptionsToJSON,
    ContainerResponseLayoutOptionsStackOptionsToJSONTyped,
} from './ContainerResponseLayoutOptionsStackOptions';
import type { ContainerResponseLayoutOptionsFluidOptions } from './ContainerResponseLayoutOptionsFluidOptions';
import {
    ContainerResponseLayoutOptionsFluidOptionsFromJSON,
    ContainerResponseLayoutOptionsFluidOptionsFromJSONTyped,
    ContainerResponseLayoutOptionsFluidOptionsToJSON,
    ContainerResponseLayoutOptionsFluidOptionsToJSONTyped,
} from './ContainerResponseLayoutOptionsFluidOptions';
import type { ContainerResponseLayoutOptionsTabOptions } from './ContainerResponseLayoutOptionsTabOptions';
import {
    ContainerResponseLayoutOptionsTabOptionsFromJSON,
    ContainerResponseLayoutOptionsTabOptionsFromJSONTyped,
    ContainerResponseLayoutOptionsTabOptionsToJSON,
    ContainerResponseLayoutOptionsTabOptionsToJSONTyped,
} from './ContainerResponseLayoutOptionsTabOptions';

/**
 * 
 * @export
 * @interface ContainerResponseLayoutOptions
 */
export interface ContainerResponseLayoutOptions {
    /**
     * 
     * @type {string}
     * @memberof ContainerResponseLayoutOptions
     */
    layout: string;
    /**
     * 
     * @type {ContainerResponseLayoutOptionsGridOptions}
     * @memberof ContainerResponseLayoutOptions
     */
    gridOptions?: ContainerResponseLayoutOptionsGridOptions;
    /**
     * 
     * @type {ContainerResponseLayoutOptionsStackOptions}
     * @memberof ContainerResponseLayoutOptions
     */
    stackOptions?: ContainerResponseLayoutOptionsStackOptions;
    /**
     * 
     * @type {ContainerResponseLayoutOptionsTabOptions}
     * @memberof ContainerResponseLayoutOptions
     */
    tabOptions?: ContainerResponseLayoutOptionsTabOptions;
    /**
     * 
     * @type {ContainerResponseLayoutOptionsFluidOptions}
     * @memberof ContainerResponseLayoutOptions
     */
    fluidOptions?: ContainerResponseLayoutOptionsFluidOptions;
}

/**
 * Check if a given object implements the ContainerResponseLayoutOptions interface.
 */
export function instanceOfContainerResponseLayoutOptions(value: object): value is ContainerResponseLayoutOptions {
    if (!('layout' in value) || value['layout'] === undefined) return false;
    return true;
}

export function ContainerResponseLayoutOptionsFromJSON(json: any): ContainerResponseLayoutOptions {
    return ContainerResponseLayoutOptionsFromJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseLayoutOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'layout': json['layout'],
        'gridOptions': json['gridOptions'] == null ? undefined : ContainerResponseLayoutOptionsGridOptionsFromJSON(json['gridOptions']),
        'stackOptions': json['stackOptions'] == null ? undefined : ContainerResponseLayoutOptionsStackOptionsFromJSON(json['stackOptions']),
        'tabOptions': json['tabOptions'] == null ? undefined : ContainerResponseLayoutOptionsTabOptionsFromJSON(json['tabOptions']),
        'fluidOptions': json['fluidOptions'] == null ? undefined : ContainerResponseLayoutOptionsFluidOptionsFromJSON(json['fluidOptions']),
    };
}

export function ContainerResponseLayoutOptionsToJSON(json: any): ContainerResponseLayoutOptions {
    return ContainerResponseLayoutOptionsToJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsToJSONTyped(value?: ContainerResponseLayoutOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layout': value['layout'],
        'gridOptions': ContainerResponseLayoutOptionsGridOptionsToJSON(value['gridOptions']),
        'stackOptions': ContainerResponseLayoutOptionsStackOptionsToJSON(value['stackOptions']),
        'tabOptions': ContainerResponseLayoutOptionsTabOptionsToJSON(value['tabOptions']),
        'fluidOptions': ContainerResponseLayoutOptionsFluidOptionsToJSON(value['fluidOptions']),
    };
}

