/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerResponseLayoutOptionsGridOptionsDefaultSize
 */
export interface ContainerResponseLayoutOptionsGridOptionsDefaultSize {
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsGridOptionsDefaultSize
     */
    xs?: number;
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsGridOptionsDefaultSize
     */
    sm?: number;
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsGridOptionsDefaultSize
     */
    md?: number;
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsGridOptionsDefaultSize
     */
    lg?: number;
    /**
     * 
     * @type {number}
     * @memberof ContainerResponseLayoutOptionsGridOptionsDefaultSize
     */
    xl?: number;
}

/**
 * Check if a given object implements the ContainerResponseLayoutOptionsGridOptionsDefaultSize interface.
 */
export function instanceOfContainerResponseLayoutOptionsGridOptionsDefaultSize(value: object): value is ContainerResponseLayoutOptionsGridOptionsDefaultSize {
    return true;
}

export function ContainerResponseLayoutOptionsGridOptionsDefaultSizeFromJSON(json: any): ContainerResponseLayoutOptionsGridOptionsDefaultSize {
    return ContainerResponseLayoutOptionsGridOptionsDefaultSizeFromJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsGridOptionsDefaultSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponseLayoutOptionsGridOptionsDefaultSize {
    if (json == null) {
        return json;
    }
    return {
        
        'xs': json['xs'] == null ? undefined : json['xs'],
        'sm': json['sm'] == null ? undefined : json['sm'],
        'md': json['md'] == null ? undefined : json['md'],
        'lg': json['lg'] == null ? undefined : json['lg'],
        'xl': json['xl'] == null ? undefined : json['xl'],
    };
}

export function ContainerResponseLayoutOptionsGridOptionsDefaultSizeToJSON(json: any): ContainerResponseLayoutOptionsGridOptionsDefaultSize {
    return ContainerResponseLayoutOptionsGridOptionsDefaultSizeToJSONTyped(json, false);
}

export function ContainerResponseLayoutOptionsGridOptionsDefaultSizeToJSONTyped(value?: ContainerResponseLayoutOptionsGridOptionsDefaultSize | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'xs': value['xs'],
        'sm': value['sm'],
        'md': value['md'],
        'lg': value['lg'],
        'xl': value['xl'],
    };
}

