/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateToken422ResponseError } from './CreateToken422ResponseError';
import {
    CreateToken422ResponseErrorFromJSON,
    CreateToken422ResponseErrorFromJSONTyped,
    CreateToken422ResponseErrorToJSON,
    CreateToken422ResponseErrorToJSONTyped,
} from './CreateToken422ResponseError';

/**
 * 
 * @export
 * @interface CreateToken422Response
 */
export interface CreateToken422Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateToken422Response
     */
    success: boolean;
    /**
     * 
     * @type {CreateToken422ResponseError}
     * @memberof CreateToken422Response
     */
    error: CreateToken422ResponseError;
}

/**
 * Check if a given object implements the CreateToken422Response interface.
 */
export function instanceOfCreateToken422Response(value: object): value is CreateToken422Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function CreateToken422ResponseFromJSON(json: any): CreateToken422Response {
    return CreateToken422ResponseFromJSONTyped(json, false);
}

export function CreateToken422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateToken422Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': CreateToken422ResponseErrorFromJSON(json['error']),
    };
}

export function CreateToken422ResponseToJSON(json: any): CreateToken422Response {
    return CreateToken422ResponseToJSONTyped(json, false);
}

export function CreateToken422ResponseToJSONTyped(value?: CreateToken422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': CreateToken422ResponseErrorToJSON(value['error']),
    };
}

