/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetColorsByMode422ResponseErrorIssuesInner } from './GetColorsByMode422ResponseErrorIssuesInner';
import {
    GetColorsByMode422ResponseErrorIssuesInnerFromJSON,
    GetColorsByMode422ResponseErrorIssuesInnerFromJSONTyped,
    GetColorsByMode422ResponseErrorIssuesInnerToJSON,
    GetColorsByMode422ResponseErrorIssuesInnerToJSONTyped,
} from './GetColorsByMode422ResponseErrorIssuesInner';

/**
 * 
 * @export
 * @interface CreateToken422ResponseError
 */
export interface CreateToken422ResponseError {
    /**
     * 
     * @type {Array<GetColorsByMode422ResponseErrorIssuesInner>}
     * @memberof CreateToken422ResponseError
     */
    issues: Array<GetColorsByMode422ResponseErrorIssuesInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateToken422ResponseError
     */
    name: string;
}

/**
 * Check if a given object implements the CreateToken422ResponseError interface.
 */
export function instanceOfCreateToken422ResponseError(value: object): value is CreateToken422ResponseError {
    if (!('issues' in value) || value['issues'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateToken422ResponseErrorFromJSON(json: any): CreateToken422ResponseError {
    return CreateToken422ResponseErrorFromJSONTyped(json, false);
}

export function CreateToken422ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateToken422ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'issues': ((json['issues'] as Array<any>).map(GetColorsByMode422ResponseErrorIssuesInnerFromJSON)),
        'name': json['name'],
    };
}

export function CreateToken422ResponseErrorToJSON(json: any): CreateToken422ResponseError {
    return CreateToken422ResponseErrorToJSONTyped(json, false);
}

export function CreateToken422ResponseErrorToJSONTyped(value?: CreateToken422ResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issues': ((value['issues'] as Array<any>).map(GetColorsByMode422ResponseErrorIssuesInnerToJSON)),
        'name': value['name'],
    };
}

