/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTokenResponse
 */
export interface CreateTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    customerUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    shippingAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    billingAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTokenResponse
     */
    storeUser: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTokenResponse
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    language: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTokenResponse
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTokenResponse
     */
    v?: number;
}

/**
 * Check if a given object implements the CreateTokenResponse interface.
 */
export function instanceOfCreateTokenResponse(value: object): value is CreateTokenResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('storeUser' in value) || value['storeUser'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function CreateTokenResponseFromJSON(json: any): CreateTokenResponse {
    return CreateTokenResponseFromJSONTyped(json, false);
}

export function CreateTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'phone': json['phone'],
        'customerUserId': json['customerUserId'] == null ? undefined : json['customerUserId'],
        'country': json['country'] == null ? undefined : json['country'],
        'shippingAddress': json['shippingAddress'] == null ? undefined : json['shippingAddress'],
        'billingAddress': json['billingAddress'] == null ? undefined : json['billingAddress'],
        'storeUser': json['storeUser'],
        'active': json['active'] == null ? undefined : json['active'],
        'language': json['language'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'id': json['_id'] == null ? undefined : json['_id'],
        'v': json['__v'] == null ? undefined : json['__v'],
    };
}

export function CreateTokenResponseToJSON(json: any): CreateTokenResponse {
    return CreateTokenResponseToJSONTyped(json, false);
}

export function CreateTokenResponseToJSONTyped(value?: CreateTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'customerUserId': value['customerUserId'],
        'country': value['country'],
        'shippingAddress': value['shippingAddress'],
        'billingAddress': value['billingAddress'],
        'storeUser': value['storeUser'],
        'active': value['active'],
        'language': value['language'],
        'currency': value['currency'],
        '_id': value['id'],
        '__v': value['v'],
    };
}

