/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElementResponseItemsInner
 */
export interface ElementResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ElementResponseItemsInner
     */
    itemType: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseItemsInner
     */
    itemId: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseItemsInner
     */
    id?: string;
}

/**
 * Check if a given object implements the ElementResponseItemsInner interface.
 */
export function instanceOfElementResponseItemsInner(value: object): value is ElementResponseItemsInner {
    if (!('itemType' in value) || value['itemType'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    return true;
}

export function ElementResponseItemsInnerFromJSON(json: any): ElementResponseItemsInner {
    return ElementResponseItemsInnerFromJSONTyped(json, false);
}

export function ElementResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'itemType': json['itemType'],
        'itemId': json['itemId'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function ElementResponseItemsInnerToJSON(json: any): ElementResponseItemsInner {
    return ElementResponseItemsInnerToJSONTyped(json, false);
}

export function ElementResponseItemsInnerToJSONTyped(value?: ElementResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemType': value['itemType'],
        'itemId': value['itemId'],
        '_id': value['id'],
    };
}

