/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseAvailableInner } from './PageResponseAvailableInner';
import {
    PageResponseAvailableInnerFromJSON,
    PageResponseAvailableInnerFromJSONTyped,
    PageResponseAvailableInnerToJSON,
    PageResponseAvailableInnerToJSONTyped,
} from './PageResponseAvailableInner';
import type { ElementResponseCardOptions } from './ElementResponseCardOptions';
import {
    ElementResponseCardOptionsFromJSON,
    ElementResponseCardOptionsFromJSONTyped,
    ElementResponseCardOptionsToJSON,
    ElementResponseCardOptionsToJSONTyped,
} from './ElementResponseCardOptions';
import type { ElementResponseItemsInner } from './ElementResponseItemsInner';
import {
    ElementResponseItemsInnerFromJSON,
    ElementResponseItemsInnerFromJSONTyped,
    ElementResponseItemsInnerToJSON,
    ElementResponseItemsInnerToJSONTyped,
} from './ElementResponseItemsInner';
import type { ElementResponseTitleInner } from './ElementResponseTitleInner';
import {
    ElementResponseTitleInnerFromJSON,
    ElementResponseTitleInnerFromJSONTyped,
    ElementResponseTitleInnerToJSON,
    ElementResponseTitleInnerToJSONTyped,
} from './ElementResponseTitleInner';
import type { ElementResponseSwiperOptions } from './ElementResponseSwiperOptions';
import {
    ElementResponseSwiperOptionsFromJSON,
    ElementResponseSwiperOptionsFromJSONTyped,
    ElementResponseSwiperOptionsToJSON,
    ElementResponseSwiperOptionsToJSONTyped,
} from './ElementResponseSwiperOptions';
import type { PageResponseNumberItems } from './PageResponseNumberItems';
import {
    PageResponseNumberItemsFromJSON,
    PageResponseNumberItemsFromJSONTyped,
    PageResponseNumberItemsToJSON,
    PageResponseNumberItemsToJSONTyped,
} from './PageResponseNumberItems';
import type { ElementResponseDescriptionInner } from './ElementResponseDescriptionInner';
import {
    ElementResponseDescriptionInnerFromJSON,
    ElementResponseDescriptionInnerFromJSONTyped,
    ElementResponseDescriptionInnerToJSON,
    ElementResponseDescriptionInnerToJSONTyped,
} from './ElementResponseDescriptionInner';

/**
 * 
 * @export
 * @interface ElementResponse
 */
export interface ElementResponse {
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    componentType: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    referenceName: string;
    /**
     * 
     * @type {Array<ElementResponseItemsInner>}
     * @memberof ElementResponse
     */
    items: Array<ElementResponseItemsInner>;
    /**
     * 
     * @type {Array<PageResponseAvailableInner>}
     * @memberof ElementResponse
     */
    availability?: Array<PageResponseAvailableInner>;
    /**
     * 
     * @type {PageResponseNumberItems}
     * @memberof ElementResponse
     */
    numberItems?: PageResponseNumberItems;
    /**
     * 
     * @type {Array<ElementResponseTitleInner>}
     * @memberof ElementResponse
     */
    title?: Array<ElementResponseTitleInner>;
    /**
     * 
     * @type {Array<ElementResponseDescriptionInner>}
     * @memberof ElementResponse
     */
    description?: Array<ElementResponseDescriptionInner>;
    /**
     * 
     * @type {boolean}
     * @memberof ElementResponse
     */
    draft?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ElementResponse
     */
    withText?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ElementResponse
     */
    withDescription?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ElementResponse
     */
    publish?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    viewText?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    viewAll?: string;
    /**
     * 
     * @type {ElementResponseSwiperOptions}
     * @memberof ElementResponse
     */
    swiperOptions?: ElementResponseSwiperOptions;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    audioUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    videoUrl?: string;
    /**
     * 
     * @type {ElementResponseCardOptions}
     * @memberof ElementResponse
     */
    cardOptions?: ElementResponseCardOptions;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    hoverEffect?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ElementResponse interface.
 */
export function instanceOfElementResponse(value: object): value is ElementResponse {
    if (!('componentType' in value) || value['componentType'] === undefined) return false;
    if (!('referenceName' in value) || value['referenceName'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ElementResponseFromJSON(json: any): ElementResponse {
    return ElementResponseFromJSONTyped(json, false);
}

export function ElementResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'componentType': json['componentType'],
        'referenceName': json['referenceName'],
        'items': ((json['items'] as Array<any>).map(ElementResponseItemsInnerFromJSON)),
        'availability': json['availability'] == null ? undefined : ((json['availability'] as Array<any>).map(PageResponseAvailableInnerFromJSON)),
        'numberItems': json['numberItems'] == null ? undefined : PageResponseNumberItemsFromJSON(json['numberItems']),
        'title': json['title'] == null ? undefined : ((json['title'] as Array<any>).map(ElementResponseTitleInnerFromJSON)),
        'description': json['description'] == null ? undefined : ((json['description'] as Array<any>).map(ElementResponseDescriptionInnerFromJSON)),
        'draft': json['draft'] == null ? undefined : json['draft'],
        'withText': json['withText'] == null ? undefined : json['withText'],
        'withDescription': json['withDescription'] == null ? undefined : json['withDescription'],
        'publish': json['publish'] == null ? undefined : json['publish'],
        'viewText': json['viewText'] == null ? undefined : json['viewText'],
        'viewAll': json['viewAll'] == null ? undefined : json['viewAll'],
        'swiperOptions': json['swiperOptions'] == null ? undefined : ElementResponseSwiperOptionsFromJSON(json['swiperOptions']),
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'audioUrl': json['audioUrl'] == null ? undefined : json['audioUrl'],
        'videoUrl': json['videoUrl'] == null ? undefined : json['videoUrl'],
        'cardOptions': json['cardOptions'] == null ? undefined : ElementResponseCardOptionsFromJSON(json['cardOptions']),
        'hoverEffect': json['hoverEffect'] == null ? undefined : json['hoverEffect'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function ElementResponseToJSON(json: any): ElementResponse {
    return ElementResponseToJSONTyped(json, false);
}

export function ElementResponseToJSONTyped(value?: ElementResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'componentType': value['componentType'],
        'referenceName': value['referenceName'],
        'items': ((value['items'] as Array<any>).map(ElementResponseItemsInnerToJSON)),
        'availability': value['availability'] == null ? undefined : ((value['availability'] as Array<any>).map(PageResponseAvailableInnerToJSON)),
        'numberItems': PageResponseNumberItemsToJSON(value['numberItems']),
        'title': value['title'] == null ? undefined : ((value['title'] as Array<any>).map(ElementResponseTitleInnerToJSON)),
        'description': value['description'] == null ? undefined : ((value['description'] as Array<any>).map(ElementResponseDescriptionInnerToJSON)),
        'draft': value['draft'],
        'withText': value['withText'],
        'withDescription': value['withDescription'],
        'publish': value['publish'],
        'viewText': value['viewText'],
        'viewAll': value['viewAll'],
        'swiperOptions': ElementResponseSwiperOptionsToJSON(value['swiperOptions']),
        'imageUrl': value['imageUrl'],
        'audioUrl': value['audioUrl'],
        'videoUrl': value['videoUrl'],
        'cardOptions': ElementResponseCardOptionsToJSON(value['cardOptions']),
        'hoverEffect': value['hoverEffect'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

