/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElementResponseCardOptions
 */
export interface ElementResponseCardOptions {
    /**
     * 
     * @type {string}
     * @memberof ElementResponseCardOptions
     */
    imagePosition?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseCardOptions
     */
    titlePosition?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseCardOptions
     */
    descriptionPosition?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseCardOptions
     */
    actionButtonPosition?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseCardOptions
     */
    actionButtonText?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseCardOptions
     */
    actionButtonUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseCardOptions
     */
    cardAspectRatio?: string;
}

/**
 * Check if a given object implements the ElementResponseCardOptions interface.
 */
export function instanceOfElementResponseCardOptions(value: object): value is ElementResponseCardOptions {
    return true;
}

export function ElementResponseCardOptionsFromJSON(json: any): ElementResponseCardOptions {
    return ElementResponseCardOptionsFromJSONTyped(json, false);
}

export function ElementResponseCardOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementResponseCardOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'imagePosition': json['imagePosition'] == null ? undefined : json['imagePosition'],
        'titlePosition': json['titlePosition'] == null ? undefined : json['titlePosition'],
        'descriptionPosition': json['descriptionPosition'] == null ? undefined : json['descriptionPosition'],
        'actionButtonPosition': json['actionButtonPosition'] == null ? undefined : json['actionButtonPosition'],
        'actionButtonText': json['actionButtonText'] == null ? undefined : json['actionButtonText'],
        'actionButtonUrl': json['actionButtonUrl'] == null ? undefined : json['actionButtonUrl'],
        'cardAspectRatio': json['cardAspectRatio'] == null ? undefined : json['cardAspectRatio'],
    };
}

export function ElementResponseCardOptionsToJSON(json: any): ElementResponseCardOptions {
    return ElementResponseCardOptionsToJSONTyped(json, false);
}

export function ElementResponseCardOptionsToJSONTyped(value?: ElementResponseCardOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imagePosition': value['imagePosition'],
        'titlePosition': value['titlePosition'],
        'descriptionPosition': value['descriptionPosition'],
        'actionButtonPosition': value['actionButtonPosition'],
        'actionButtonText': value['actionButtonText'],
        'actionButtonUrl': value['actionButtonUrl'],
        'cardAspectRatio': value['cardAspectRatio'],
    };
}

