/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElementResponseSwiperOptions
 */
export interface ElementResponseSwiperOptions {
    /**
     * 
     * @type {number}
     * @memberof ElementResponseSwiperOptions
     */
    slidesPerView?: number;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseSwiperOptions
     */
    swiperType?: string;
    /**
     * 
     * @type {number}
     * @memberof ElementResponseSwiperOptions
     */
    spaceBetween?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ElementResponseSwiperOptions
     */
    loop?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ElementResponseSwiperOptions
     */
    autoplayDelay?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ElementResponseSwiperOptions
     */
    autoplayDisableOnInteraction?: boolean;
    /**
     * 
     * @type {any}
     * @memberof ElementResponseSwiperOptions
     */
    breakpoints?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseSwiperOptions
     */
    effect?: string;
    /**
     * 
     * @type {number}
     * @memberof ElementResponseSwiperOptions
     */
    speed?: number;
}

/**
 * Check if a given object implements the ElementResponseSwiperOptions interface.
 */
export function instanceOfElementResponseSwiperOptions(value: object): value is ElementResponseSwiperOptions {
    return true;
}

export function ElementResponseSwiperOptionsFromJSON(json: any): ElementResponseSwiperOptions {
    return ElementResponseSwiperOptionsFromJSONTyped(json, false);
}

export function ElementResponseSwiperOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementResponseSwiperOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'slidesPerView': json['slidesPerView'] == null ? undefined : json['slidesPerView'],
        'swiperType': json['swiperType'] == null ? undefined : json['swiperType'],
        'spaceBetween': json['spaceBetween'] == null ? undefined : json['spaceBetween'],
        'loop': json['loop'] == null ? undefined : json['loop'],
        'autoplayDelay': json['autoplay.delay'] == null ? undefined : json['autoplay.delay'],
        'autoplayDisableOnInteraction': json['autoplay.disableOnInteraction'] == null ? undefined : json['autoplay.disableOnInteraction'],
        'breakpoints': json['breakpoints'] == null ? undefined : json['breakpoints'],
        'effect': json['effect'] == null ? undefined : json['effect'],
        'speed': json['speed'] == null ? undefined : json['speed'],
    };
}

export function ElementResponseSwiperOptionsToJSON(json: any): ElementResponseSwiperOptions {
    return ElementResponseSwiperOptionsToJSONTyped(json, false);
}

export function ElementResponseSwiperOptionsToJSONTyped(value?: ElementResponseSwiperOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slidesPerView': value['slidesPerView'],
        'swiperType': value['swiperType'],
        'spaceBetween': value['spaceBetween'],
        'loop': value['loop'],
        'autoplay.delay': value['autoplayDelay'],
        'autoplay.disableOnInteraction': value['autoplayDisableOnInteraction'],
        'breakpoints': value['breakpoints'],
        'effect': value['effect'],
        'speed': value['speed'],
    };
}

