/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElementResponseDescriptionInner
 */
export interface ElementResponseDescriptionInner {
    /**
     * 
     * @type {string}
     * @memberof ElementResponseDescriptionInner
     */
    lanCode: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseDescriptionInner
     */
    paragraph: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseDescriptionInner
     */
    id?: string;
}

/**
 * Check if a given object implements the ElementResponseDescriptionInner interface.
 */
export function instanceOfElementResponseDescriptionInner(value: object): value is ElementResponseDescriptionInner {
    if (!('lanCode' in value) || value['lanCode'] === undefined) return false;
    if (!('paragraph' in value) || value['paragraph'] === undefined) return false;
    return true;
}

export function ElementResponseDescriptionInnerFromJSON(json: any): ElementResponseDescriptionInner {
    return ElementResponseDescriptionInnerFromJSONTyped(json, false);
}

export function ElementResponseDescriptionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementResponseDescriptionInner {
    if (json == null) {
        return json;
    }
    return {
        
        'lanCode': json['lanCode'],
        'paragraph': json['paragraph'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function ElementResponseDescriptionInnerToJSON(json: any): ElementResponseDescriptionInner {
    return ElementResponseDescriptionInnerToJSONTyped(json, false);
}

export function ElementResponseDescriptionInnerToJSONTyped(value?: ElementResponseDescriptionInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lanCode': value['lanCode'],
        'paragraph': value['paragraph'],
        '_id': value['id'],
    };
}

