/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ElementResponseTitleInner
 */
export interface ElementResponseTitleInner {
    /**
     * 
     * @type {string}
     * @memberof ElementResponseTitleInner
     */
    lanCode: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseTitleInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ElementResponseTitleInner
     */
    id?: string;
}

/**
 * Check if a given object implements the ElementResponseTitleInner interface.
 */
export function instanceOfElementResponseTitleInner(value: object): value is ElementResponseTitleInner {
    if (!('lanCode' in value) || value['lanCode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ElementResponseTitleInnerFromJSON(json: any): ElementResponseTitleInner {
    return ElementResponseTitleInnerFromJSONTyped(json, false);
}

export function ElementResponseTitleInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ElementResponseTitleInner {
    if (json == null) {
        return json;
    }
    return {
        
        'lanCode': json['lanCode'],
        'name': json['name'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function ElementResponseTitleInnerToJSON(json: any): ElementResponseTitleInner {
    return ElementResponseTitleInnerToJSONTyped(json, false);
}

export function ElementResponseTitleInnerToJSONTyped(value?: ElementResponseTitleInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lanCode': value['lanCode'],
        'name': value['name'],
        '_id': value['id'],
    };
}

