/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetColorsByMode422ResponseError } from './GetColorsByMode422ResponseError';
import {
    GetColorsByMode422ResponseErrorFromJSON,
    GetColorsByMode422ResponseErrorFromJSONTyped,
    GetColorsByMode422ResponseErrorToJSON,
    GetColorsByMode422ResponseErrorToJSONTyped,
} from './GetColorsByMode422ResponseError';

/**
 * 
 * @export
 * @interface GetColorsByMode422Response
 */
export interface GetColorsByMode422Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetColorsByMode422Response
     */
    success: boolean;
    /**
     * 
     * @type {GetColorsByMode422ResponseError}
     * @memberof GetColorsByMode422Response
     */
    error: GetColorsByMode422ResponseError;
}

/**
 * Check if a given object implements the GetColorsByMode422Response interface.
 */
export function instanceOfGetColorsByMode422Response(value: object): value is GetColorsByMode422Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetColorsByMode422ResponseFromJSON(json: any): GetColorsByMode422Response {
    return GetColorsByMode422ResponseFromJSONTyped(json, false);
}

export function GetColorsByMode422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetColorsByMode422Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': GetColorsByMode422ResponseErrorFromJSON(json['error']),
    };
}

export function GetColorsByMode422ResponseToJSON(json: any): GetColorsByMode422Response {
    return GetColorsByMode422ResponseToJSONTyped(json, false);
}

export function GetColorsByMode422ResponseToJSONTyped(value?: GetColorsByMode422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': GetColorsByMode422ResponseErrorToJSON(value['error']),
    };
}

