/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetColorsByMode422ResponseErrorIssuesInnerPathInner } from './GetColorsByMode422ResponseErrorIssuesInnerPathInner';
import {
    GetColorsByMode422ResponseErrorIssuesInnerPathInnerFromJSON,
    GetColorsByMode422ResponseErrorIssuesInnerPathInnerFromJSONTyped,
    GetColorsByMode422ResponseErrorIssuesInnerPathInnerToJSON,
    GetColorsByMode422ResponseErrorIssuesInnerPathInnerToJSONTyped,
} from './GetColorsByMode422ResponseErrorIssuesInnerPathInner';

/**
 * 
 * @export
 * @interface GetColorsByMode422ResponseErrorIssuesInner
 */
export interface GetColorsByMode422ResponseErrorIssuesInner {
    /**
     * 
     * @type {string}
     * @memberof GetColorsByMode422ResponseErrorIssuesInner
     */
    code: string;
    /**
     * 
     * @type {Array<GetColorsByMode422ResponseErrorIssuesInnerPathInner>}
     * @memberof GetColorsByMode422ResponseErrorIssuesInner
     */
    path: Array<GetColorsByMode422ResponseErrorIssuesInnerPathInner>;
    /**
     * 
     * @type {string}
     * @memberof GetColorsByMode422ResponseErrorIssuesInner
     */
    message?: string;
}

/**
 * Check if a given object implements the GetColorsByMode422ResponseErrorIssuesInner interface.
 */
export function instanceOfGetColorsByMode422ResponseErrorIssuesInner(value: object): value is GetColorsByMode422ResponseErrorIssuesInner {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function GetColorsByMode422ResponseErrorIssuesInnerFromJSON(json: any): GetColorsByMode422ResponseErrorIssuesInner {
    return GetColorsByMode422ResponseErrorIssuesInnerFromJSONTyped(json, false);
}

export function GetColorsByMode422ResponseErrorIssuesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetColorsByMode422ResponseErrorIssuesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'path': ((json['path'] as Array<any>).map(GetColorsByMode422ResponseErrorIssuesInnerPathInnerFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function GetColorsByMode422ResponseErrorIssuesInnerToJSON(json: any): GetColorsByMode422ResponseErrorIssuesInner {
    return GetColorsByMode422ResponseErrorIssuesInnerToJSONTyped(json, false);
}

export function GetColorsByMode422ResponseErrorIssuesInnerToJSONTyped(value?: GetColorsByMode422ResponseErrorIssuesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'path': ((value['path'] as Array<any>).map(GetColorsByMode422ResponseErrorIssuesInnerPathInnerToJSON)),
        'message': value['message'],
    };
}

