/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetColorsByMode404Response
 */
export interface GetColorsByMode404Response {
    /**
     * 
     * @type {string}
     * @memberof GetColorsByMode404Response
     */
    message: string;
}

/**
 * Check if a given object implements the GetColorsByMode404Response interface.
 */
export function instanceOfGetColorsByMode404Response(value: object): value is GetColorsByMode404Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetColorsByMode404ResponseFromJSON(json: any): GetColorsByMode404Response {
    return GetColorsByMode404ResponseFromJSONTyped(json, false);
}

export function GetColorsByMode404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetColorsByMode404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function GetColorsByMode404ResponseToJSON(json: any): GetColorsByMode404Response {
    return GetColorsByMode404ResponseToJSONTyped(json, false);
}

export function GetColorsByMode404ResponseToJSONTyped(value?: GetColorsByMode404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

