/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetColorsByMode422ResponseErrorIssuesInnerPathInner
 */
export interface GetColorsByMode422ResponseErrorIssuesInnerPathInner {
}

/**
 * Check if a given object implements the GetColorsByMode422ResponseErrorIssuesInnerPathInner interface.
 */
export function instanceOfGetColorsByMode422ResponseErrorIssuesInnerPathInner(value: object): value is GetColorsByMode422ResponseErrorIssuesInnerPathInner {
    return true;
}

export function GetColorsByMode422ResponseErrorIssuesInnerPathInnerFromJSON(json: any): GetColorsByMode422ResponseErrorIssuesInnerPathInner {
    return GetColorsByMode422ResponseErrorIssuesInnerPathInnerFromJSONTyped(json, false);
}

export function GetColorsByMode422ResponseErrorIssuesInnerPathInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetColorsByMode422ResponseErrorIssuesInnerPathInner {
    return json;
}

export function GetColorsByMode422ResponseErrorIssuesInnerPathInnerToJSON(json: any): GetColorsByMode422ResponseErrorIssuesInnerPathInner {
    return GetColorsByMode422ResponseErrorIssuesInnerPathInnerToJSONTyped(json, false);
}

export function GetColorsByMode422ResponseErrorIssuesInnerPathInnerToJSONTyped(value?: GetColorsByMode422ResponseErrorIssuesInnerPathInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

