/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayoutResponseLogosInner
 */
export interface LayoutResponseLogosInner {
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseLogosInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseLogosInner
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseLogosInner
     */
    id?: string;
}

/**
 * Check if a given object implements the LayoutResponseLogosInner interface.
 */
export function instanceOfLayoutResponseLogosInner(value: object): value is LayoutResponseLogosInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function LayoutResponseLogosInnerFromJSON(json: any): LayoutResponseLogosInner {
    return LayoutResponseLogosInnerFromJSONTyped(json, false);
}

export function LayoutResponseLogosInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutResponseLogosInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'imageUrl': json['imageUrl'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function LayoutResponseLogosInnerToJSON(json: any): LayoutResponseLogosInner {
    return LayoutResponseLogosInnerToJSONTyped(json, false);
}

export function LayoutResponseLogosInnerToJSONTyped(value?: LayoutResponseLogosInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'imageUrl': value['imageUrl'],
        '_id': value['id'],
    };
}

