/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayoutResponseFontSize
 */
export interface LayoutResponseFontSize {
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontSize
     */
    base?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontSize
     */
    xs?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontSize
     */
    sm?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontSize
     */
    md?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontSize
     */
    lg?: string;
}

/**
 * Check if a given object implements the LayoutResponseFontSize interface.
 */
export function instanceOfLayoutResponseFontSize(value: object): value is LayoutResponseFontSize {
    return true;
}

export function LayoutResponseFontSizeFromJSON(json: any): LayoutResponseFontSize {
    return LayoutResponseFontSizeFromJSONTyped(json, false);
}

export function LayoutResponseFontSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutResponseFontSize {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'] == null ? undefined : json['base'],
        'xs': json['xs'] == null ? undefined : json['xs'],
        'sm': json['sm'] == null ? undefined : json['sm'],
        'md': json['md'] == null ? undefined : json['md'],
        'lg': json['lg'] == null ? undefined : json['lg'],
    };
}

export function LayoutResponseFontSizeToJSON(json: any): LayoutResponseFontSize {
    return LayoutResponseFontSizeToJSONTyped(json, false);
}

export function LayoutResponseFontSizeToJSONTyped(value?: LayoutResponseFontSize | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'xs': value['xs'],
        'sm': value['sm'],
        'md': value['md'],
        'lg': value['lg'],
    };
}

