/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LayoutResponseFontSize } from './LayoutResponseFontSize';
import {
    LayoutResponseFontSizeFromJSON,
    LayoutResponseFontSizeFromJSONTyped,
    LayoutResponseFontSizeToJSON,
    LayoutResponseFontSizeToJSONTyped,
} from './LayoutResponseFontSize';
import type { LayoutResponseLogosInner } from './LayoutResponseLogosInner';
import {
    LayoutResponseLogosInnerFromJSON,
    LayoutResponseLogosInnerFromJSONTyped,
    LayoutResponseLogosInnerToJSON,
    LayoutResponseLogosInnerToJSONTyped,
} from './LayoutResponseLogosInner';
import type { LayoutResponseFontInner } from './LayoutResponseFontInner';
import {
    LayoutResponseFontInnerFromJSON,
    LayoutResponseFontInnerFromJSONTyped,
    LayoutResponseFontInnerToJSON,
    LayoutResponseFontInnerToJSONTyped,
} from './LayoutResponseFontInner';

/**
 * 
 * @export
 * @interface LayoutResponse
 */
export interface LayoutResponse {
    /**
     * 
     * @type {Array<LayoutResponseFontInner>}
     * @memberof LayoutResponse
     */
    font?: Array<LayoutResponseFontInner>;
    /**
     * 
     * @type {Array<LayoutResponseLogosInner>}
     * @memberof LayoutResponse
     */
    logos?: Array<LayoutResponseLogosInner>;
    /**
     * 
     * @type {LayoutResponseFontSize}
     * @memberof LayoutResponse
     */
    fontSize?: LayoutResponseFontSize;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the LayoutResponse interface.
 */
export function instanceOfLayoutResponse(value: object): value is LayoutResponse {
    return true;
}

export function LayoutResponseFromJSON(json: any): LayoutResponse {
    return LayoutResponseFromJSONTyped(json, false);
}

export function LayoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'font': json['font'] == null ? undefined : ((json['font'] as Array<any>).map(LayoutResponseFontInnerFromJSON)),
        'logos': json['logos'] == null ? undefined : ((json['logos'] as Array<any>).map(LayoutResponseLogosInnerFromJSON)),
        'fontSize': json['fontSize'] == null ? undefined : LayoutResponseFontSizeFromJSON(json['fontSize']),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function LayoutResponseToJSON(json: any): LayoutResponse {
    return LayoutResponseToJSONTyped(json, false);
}

export function LayoutResponseToJSONTyped(value?: LayoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'font': value['font'] == null ? undefined : ((value['font'] as Array<any>).map(LayoutResponseFontInnerToJSON)),
        'logos': value['logos'] == null ? undefined : ((value['logos'] as Array<any>).map(LayoutResponseLogosInnerToJSON)),
        'fontSize': LayoutResponseFontSizeToJSON(value['fontSize']),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

