/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayoutResponseFontInner
 */
export interface LayoutResponseFontInner {
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontInner
     */
    fontFamily: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontInner
     */
    subset?: string;
    /**
     * 
     * @type {Array<any | null>}
     * @memberof LayoutResponseFontInner
     */
    weights?: Array<any | null>;
    /**
     * 
     * @type {Array<any | null>}
     * @memberof LayoutResponseFontInner
     */
    styles?: Array<any | null>;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontInner
     */
    lanCode?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutResponseFontInner
     */
    id?: string;
}

/**
 * Check if a given object implements the LayoutResponseFontInner interface.
 */
export function instanceOfLayoutResponseFontInner(value: object): value is LayoutResponseFontInner {
    if (!('fontFamily' in value) || value['fontFamily'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function LayoutResponseFontInnerFromJSON(json: any): LayoutResponseFontInner {
    return LayoutResponseFontInnerFromJSONTyped(json, false);
}

export function LayoutResponseFontInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayoutResponseFontInner {
    if (json == null) {
        return json;
    }
    return {
        
        'fontFamily': json['fontFamily'],
        'subset': json['subset'] == null ? undefined : json['subset'],
        'weights': json['weights'] == null ? undefined : json['weights'],
        'styles': json['styles'] == null ? undefined : json['styles'],
        'type': json['type'],
        'lanCode': json['lanCode'] == null ? undefined : json['lanCode'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function LayoutResponseFontInnerToJSON(json: any): LayoutResponseFontInner {
    return LayoutResponseFontInnerToJSONTyped(json, false);
}

export function LayoutResponseFontInnerToJSONTyped(value?: LayoutResponseFontInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fontFamily': value['fontFamily'],
        'subset': value['subset'],
        'weights': value['weights'],
        'styles': value['styles'],
        'type': value['type'],
        'lanCode': value['lanCode'],
        '_id': value['id'],
    };
}

