/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MenuResponseItemsInner } from './MenuResponseItemsInner';
import {
    MenuResponseItemsInnerFromJSON,
    MenuResponseItemsInnerFromJSONTyped,
    MenuResponseItemsInnerToJSON,
    MenuResponseItemsInnerToJSONTyped,
} from './MenuResponseItemsInner';

/**
 * 
 * @export
 * @interface MenuResponse
 */
export interface MenuResponse {
    /**
     * 
     * @type {string}
     * @memberof MenuResponse
     */
    menuName: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponse
     */
    menuType: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponse
     */
    layoutType: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponse
     */
    menuPage?: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MenuResponse
     */
    allowImage?: boolean;
    /**
     * 
     * @type {Array<MenuResponseItemsInner>}
     * @memberof MenuResponse
     */
    items?: Array<MenuResponseItemsInner>;
    /**
     * 
     * @type {boolean}
     * @memberof MenuResponse
     */
    active?: boolean;
}

/**
 * Check if a given object implements the MenuResponse interface.
 */
export function instanceOfMenuResponse(value: object): value is MenuResponse {
    if (!('menuName' in value) || value['menuName'] === undefined) return false;
    if (!('menuType' in value) || value['menuType'] === undefined) return false;
    if (!('layoutType' in value) || value['layoutType'] === undefined) return false;
    return true;
}

export function MenuResponseFromJSON(json: any): MenuResponse {
    return MenuResponseFromJSONTyped(json, false);
}

export function MenuResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'menuName': json['menuName'],
        'menuType': json['menuType'],
        'layoutType': json['layoutType'],
        'menuPage': json['menuPage'] == null ? undefined : json['menuPage'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'allowImage': json['allowImage'] == null ? undefined : json['allowImage'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(MenuResponseItemsInnerFromJSON)),
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function MenuResponseToJSON(json: any): MenuResponse {
    return MenuResponseToJSONTyped(json, false);
}

export function MenuResponseToJSONTyped(value?: MenuResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'menuName': value['menuName'],
        'menuType': value['menuType'],
        'layoutType': value['layoutType'],
        'menuPage': value['menuPage'],
        'imageUrl': value['imageUrl'],
        'allowImage': value['allowImage'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(MenuResponseItemsInnerToJSON)),
        'active': value['active'],
    };
}

