/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MenuResponseItemsInnerMultiItemsInner } from './MenuResponseItemsInnerMultiItemsInner';
import {
    MenuResponseItemsInnerMultiItemsInnerFromJSON,
    MenuResponseItemsInnerMultiItemsInnerFromJSONTyped,
    MenuResponseItemsInnerMultiItemsInnerToJSON,
    MenuResponseItemsInnerMultiItemsInnerToJSONTyped,
} from './MenuResponseItemsInnerMultiItemsInner';

/**
 * 
 * @export
 * @interface MenuResponseItemsInner
 */
export interface MenuResponseItemsInner {
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInner
     */
    menuName: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInner
     */
    menuType: string;
    /**
     * 
     * @type {Array<MenuResponseItemsInnerMultiItemsInner>}
     * @memberof MenuResponseItemsInner
     */
    multiItems?: Array<MenuResponseItemsInnerMultiItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInner
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MenuResponseItemsInner
     */
    allowImage?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInner
     */
    menuPage?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MenuResponseItemsInner
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInner
     */
    id?: string;
}

/**
 * Check if a given object implements the MenuResponseItemsInner interface.
 */
export function instanceOfMenuResponseItemsInner(value: object): value is MenuResponseItemsInner {
    if (!('menuName' in value) || value['menuName'] === undefined) return false;
    if (!('menuType' in value) || value['menuType'] === undefined) return false;
    return true;
}

export function MenuResponseItemsInnerFromJSON(json: any): MenuResponseItemsInner {
    return MenuResponseItemsInnerFromJSONTyped(json, false);
}

export function MenuResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'menuName': json['menuName'],
        'menuType': json['menuType'],
        'multiItems': json['multiItems'] == null ? undefined : ((json['multiItems'] as Array<any>).map(MenuResponseItemsInnerMultiItemsInnerFromJSON)),
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'allowImage': json['allowImage'] == null ? undefined : json['allowImage'],
        'menuPage': json['menuPage'] == null ? undefined : json['menuPage'],
        'active': json['active'] == null ? undefined : json['active'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function MenuResponseItemsInnerToJSON(json: any): MenuResponseItemsInner {
    return MenuResponseItemsInnerToJSONTyped(json, false);
}

export function MenuResponseItemsInnerToJSONTyped(value?: MenuResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'menuName': value['menuName'],
        'menuType': value['menuType'],
        'multiItems': value['multiItems'] == null ? undefined : ((value['multiItems'] as Array<any>).map(MenuResponseItemsInnerMultiItemsInnerToJSON)),
        'imageUrl': value['imageUrl'],
        'allowImage': value['allowImage'],
        'menuPage': value['menuPage'],
        'active': value['active'],
        '_id': value['id'],
    };
}

