/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MenuResponseItemsInnerMultiItemsInner
 */
export interface MenuResponseItemsInnerMultiItemsInner {
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInnerMultiItemsInner
     */
    menuName: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInnerMultiItemsInner
     */
    menuType: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInnerMultiItemsInner
     */
    menuPage?: string;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInnerMultiItemsInner
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MenuResponseItemsInnerMultiItemsInner
     */
    allowImage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MenuResponseItemsInnerMultiItemsInner
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MenuResponseItemsInnerMultiItemsInner
     */
    id?: string;
}

/**
 * Check if a given object implements the MenuResponseItemsInnerMultiItemsInner interface.
 */
export function instanceOfMenuResponseItemsInnerMultiItemsInner(value: object): value is MenuResponseItemsInnerMultiItemsInner {
    if (!('menuName' in value) || value['menuName'] === undefined) return false;
    if (!('menuType' in value) || value['menuType'] === undefined) return false;
    return true;
}

export function MenuResponseItemsInnerMultiItemsInnerFromJSON(json: any): MenuResponseItemsInnerMultiItemsInner {
    return MenuResponseItemsInnerMultiItemsInnerFromJSONTyped(json, false);
}

export function MenuResponseItemsInnerMultiItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuResponseItemsInnerMultiItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'menuName': json['menuName'],
        'menuType': json['menuType'],
        'menuPage': json['menuPage'] == null ? undefined : json['menuPage'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'allowImage': json['allowImage'] == null ? undefined : json['allowImage'],
        'active': json['active'] == null ? undefined : json['active'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function MenuResponseItemsInnerMultiItemsInnerToJSON(json: any): MenuResponseItemsInnerMultiItemsInner {
    return MenuResponseItemsInnerMultiItemsInnerToJSONTyped(json, false);
}

export function MenuResponseItemsInnerMultiItemsInnerToJSONTyped(value?: MenuResponseItemsInnerMultiItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'menuName': value['menuName'],
        'menuType': value['menuType'],
        'menuPage': value['menuPage'],
        'imageUrl': value['imageUrl'],
        'allowImage': value['allowImage'],
        'active': value['active'],
        '_id': value['id'],
    };
}

