/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageResponseTitleInner
 */
export interface PageResponseTitleInner {
    /**
     * 
     * @type {string}
     * @memberof PageResponseTitleInner
     */
    lanCode: string;
    /**
     * 
     * @type {string}
     * @memberof PageResponseTitleInner
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PageResponseTitleInner
     */
    id?: string;
}

/**
 * Check if a given object implements the PageResponseTitleInner interface.
 */
export function instanceOfPageResponseTitleInner(value: object): value is PageResponseTitleInner {
    if (!('lanCode' in value) || value['lanCode'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function PageResponseTitleInnerFromJSON(json: any): PageResponseTitleInner {
    return PageResponseTitleInnerFromJSONTyped(json, false);
}

export function PageResponseTitleInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseTitleInner {
    if (json == null) {
        return json;
    }
    return {
        
        'lanCode': json['lanCode'],
        'title': json['title'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function PageResponseTitleInnerToJSON(json: any): PageResponseTitleInner {
    return PageResponseTitleInnerToJSONTyped(json, false);
}

export function PageResponseTitleInnerToJSONTyped(value?: PageResponseTitleInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lanCode': value['lanCode'],
        'title': value['title'],
        '_id': value['id'],
    };
}

