/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageResponseAvailableInner
 */
export interface PageResponseAvailableInner {
    /**
     * 
     * @type {string}
     * @memberof PageResponseAvailableInner
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof PageResponseAvailableInner
     */
    id?: string;
}

/**
 * Check if a given object implements the PageResponseAvailableInner interface.
 */
export function instanceOfPageResponseAvailableInner(value: object): value is PageResponseAvailableInner {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    return true;
}

export function PageResponseAvailableInnerFromJSON(json: any): PageResponseAvailableInner {
    return PageResponseAvailableInnerFromJSONTyped(json, false);
}

export function PageResponseAvailableInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseAvailableInner {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['appId'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function PageResponseAvailableInnerToJSON(json: any): PageResponseAvailableInner {
    return PageResponseAvailableInnerToJSONTyped(json, false);
}

export function PageResponseAvailableInnerToJSONTyped(value?: PageResponseAvailableInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appId': value['appId'],
        '_id': value['id'],
    };
}

