/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageResponseMetaDescriptionInner
 */
export interface PageResponseMetaDescriptionInner {
    /**
     * 
     * @type {string}
     * @memberof PageResponseMetaDescriptionInner
     */
    lanCode: string;
    /**
     * 
     * @type {string}
     * @memberof PageResponseMetaDescriptionInner
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PageResponseMetaDescriptionInner
     */
    id?: string;
}

/**
 * Check if a given object implements the PageResponseMetaDescriptionInner interface.
 */
export function instanceOfPageResponseMetaDescriptionInner(value: object): value is PageResponseMetaDescriptionInner {
    if (!('lanCode' in value) || value['lanCode'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PageResponseMetaDescriptionInnerFromJSON(json: any): PageResponseMetaDescriptionInner {
    return PageResponseMetaDescriptionInnerFromJSONTyped(json, false);
}

export function PageResponseMetaDescriptionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseMetaDescriptionInner {
    if (json == null) {
        return json;
    }
    return {
        
        'lanCode': json['lanCode'],
        'description': json['description'],
        'id': json['_id'] == null ? undefined : json['_id'],
    };
}

export function PageResponseMetaDescriptionInnerToJSON(json: any): PageResponseMetaDescriptionInner {
    return PageResponseMetaDescriptionInnerToJSONTyped(json, false);
}

export function PageResponseMetaDescriptionInnerToJSONTyped(value?: PageResponseMetaDescriptionInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lanCode': value['lanCode'],
        'description': value['description'],
        '_id': value['id'],
    };
}

