/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseAvailableInner } from './PageResponseAvailableInner';
import {
    PageResponseAvailableInnerFromJSON,
    PageResponseAvailableInnerFromJSONTyped,
    PageResponseAvailableInnerToJSON,
    PageResponseAvailableInnerToJSONTyped,
} from './PageResponseAvailableInner';
import type { PageResponseTitleInner } from './PageResponseTitleInner';
import {
    PageResponseTitleInnerFromJSON,
    PageResponseTitleInnerFromJSONTyped,
    PageResponseTitleInnerToJSON,
    PageResponseTitleInnerToJSONTyped,
} from './PageResponseTitleInner';
import type { PageResponseNumberItems } from './PageResponseNumberItems';
import {
    PageResponseNumberItemsFromJSON,
    PageResponseNumberItemsFromJSONTyped,
    PageResponseNumberItemsToJSON,
    PageResponseNumberItemsToJSONTyped,
} from './PageResponseNumberItems';
import type { PageResponseMetaDescriptionInner } from './PageResponseMetaDescriptionInner';
import {
    PageResponseMetaDescriptionInnerFromJSON,
    PageResponseMetaDescriptionInnerFromJSONTyped,
    PageResponseMetaDescriptionInnerToJSON,
    PageResponseMetaDescriptionInnerToJSONTyped,
} from './PageResponseMetaDescriptionInner';

/**
 * 
 * @export
 * @interface PageBySlugResponse
 */
export interface PageBySlugResponse {
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    referenceName: string;
    /**
     * 
     * @type {Array<any | null>}
     * @memberof PageBySlugResponse
     */
    items?: Array<any | null>;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    internalType: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    externalUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    bannerImage?: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    portraitImage?: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    landscapeImage?: string;
    /**
     * 
     * @type {Array<PageResponseAvailableInner>}
     * @memberof PageBySlugResponse
     */
    available?: Array<PageResponseAvailableInner>;
    /**
     * 
     * @type {PageResponseNumberItems}
     * @memberof PageBySlugResponse
     */
    numberItems?: PageResponseNumberItems;
    /**
     * 
     * @type {Array<PageResponseTitleInner>}
     * @memberof PageBySlugResponse
     */
    title: Array<PageResponseTitleInner>;
    /**
     * 
     * @type {Array<PageResponseMetaDescriptionInner>}
     * @memberof PageBySlugResponse
     */
    metaDescription: Array<PageResponseMetaDescriptionInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PageBySlugResponse
     */
    keywords?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    canonicalUrl?: string;
    /**
     * 
     * @type {Array<PageResponseTitleInner>}
     * @memberof PageBySlugResponse
     */
    ogTitle: Array<PageResponseTitleInner>;
    /**
     * 
     * @type {Array<PageResponseMetaDescriptionInner>}
     * @memberof PageBySlugResponse
     */
    ogDescription: Array<PageResponseMetaDescriptionInner>;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    ogImage?: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    twitterCard?: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    twitterCreator?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PageBySlugResponse
     */
    publish?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageBySlugResponse
     */
    draft?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PageBySlugResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the PageBySlugResponse interface.
 */
export function instanceOfPageBySlugResponse(value: object): value is PageBySlugResponse {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('referenceName' in value) || value['referenceName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('internalType' in value) || value['internalType'] === undefined) return false;
    if (!('externalUrl' in value) || value['externalUrl'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('metaDescription' in value) || value['metaDescription'] === undefined) return false;
    if (!('ogTitle' in value) || value['ogTitle'] === undefined) return false;
    if (!('ogDescription' in value) || value['ogDescription'] === undefined) return false;
    return true;
}

export function PageBySlugResponseFromJSON(json: any): PageBySlugResponse {
    return PageBySlugResponseFromJSONTyped(json, false);
}

export function PageBySlugResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageBySlugResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'referenceName': json['referenceName'],
        'items': json['items'] == null ? undefined : json['items'],
        'type': json['type'],
        'internalType': json['internalType'],
        'externalUrl': json['externalUrl'],
        'bannerImage': json['bannerImage'] == null ? undefined : json['bannerImage'],
        'portraitImage': json['portraitImage'] == null ? undefined : json['portraitImage'],
        'landscapeImage': json['landscapeImage'] == null ? undefined : json['landscapeImage'],
        'available': json['available'] == null ? undefined : ((json['available'] as Array<any>).map(PageResponseAvailableInnerFromJSON)),
        'numberItems': json['numberItems'] == null ? undefined : PageResponseNumberItemsFromJSON(json['numberItems']),
        'title': ((json['title'] as Array<any>).map(PageResponseTitleInnerFromJSON)),
        'metaDescription': ((json['metaDescription'] as Array<any>).map(PageResponseMetaDescriptionInnerFromJSON)),
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'canonicalUrl': json['canonicalUrl'] == null ? undefined : json['canonicalUrl'],
        'ogTitle': ((json['ogTitle'] as Array<any>).map(PageResponseTitleInnerFromJSON)),
        'ogDescription': ((json['ogDescription'] as Array<any>).map(PageResponseMetaDescriptionInnerFromJSON)),
        'ogImage': json['ogImage'] == null ? undefined : json['ogImage'],
        'twitterCard': json['twitterCard'] == null ? undefined : json['twitterCard'],
        'twitterCreator': json['twitterCreator'] == null ? undefined : json['twitterCreator'],
        'publish': json['publish'] == null ? undefined : json['publish'],
        'draft': json['draft'] == null ? undefined : json['draft'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function PageBySlugResponseToJSON(json: any): PageBySlugResponse {
    return PageBySlugResponseToJSONTyped(json, false);
}

export function PageBySlugResponseToJSONTyped(value?: PageBySlugResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'referenceName': value['referenceName'],
        'items': value['items'],
        'type': value['type'],
        'internalType': value['internalType'],
        'externalUrl': value['externalUrl'],
        'bannerImage': value['bannerImage'],
        'portraitImage': value['portraitImage'],
        'landscapeImage': value['landscapeImage'],
        'available': value['available'] == null ? undefined : ((value['available'] as Array<any>).map(PageResponseAvailableInnerToJSON)),
        'numberItems': PageResponseNumberItemsToJSON(value['numberItems']),
        'title': ((value['title'] as Array<any>).map(PageResponseTitleInnerToJSON)),
        'metaDescription': ((value['metaDescription'] as Array<any>).map(PageResponseMetaDescriptionInnerToJSON)),
        'keywords': value['keywords'],
        'canonicalUrl': value['canonicalUrl'],
        'ogTitle': ((value['ogTitle'] as Array<any>).map(PageResponseTitleInnerToJSON)),
        'ogDescription': ((value['ogDescription'] as Array<any>).map(PageResponseMetaDescriptionInnerToJSON)),
        'ogImage': value['ogImage'],
        'twitterCard': value['twitterCard'],
        'twitterCreator': value['twitterCreator'],
        'publish': value['publish'],
        'draft': value['draft'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

