/* tslint:disable */
/* eslint-disable */
/**
 * Nexalogics Consumer API
 * <p>Document describing the contracts used for all REST APIs exposed by Nexaalogics Consumer App.</p>       <p>Some useful links:</p>       <ul>       <li><a href=\"https://dev.nexalogics.com.au/\">Nexa Admin API Staging</a></li>       <li><a href=\"https://adminapi.nexalogics.com.au/\">Nexa Admin API Production</a></li>       <li><a href=\"https://staging.nexalogics.com.au/\">Nexa Admin Staging</a></li>       <li><a href=\"https://admin.nexalogics.com.au/\">Nexa Admin Production</a></li>       </ul>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@nexalogics.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageResponseNumberItems
 */
export interface PageResponseNumberItems {
    /**
     * 
     * @type {number}
     * @memberof PageResponseNumberItems
     */
    web?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseNumberItems
     */
    android?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseNumberItems
     */
    iOS?: number;
}

/**
 * Check if a given object implements the PageResponseNumberItems interface.
 */
export function instanceOfPageResponseNumberItems(value: object): value is PageResponseNumberItems {
    return true;
}

export function PageResponseNumberItemsFromJSON(json: any): PageResponseNumberItems {
    return PageResponseNumberItemsFromJSONTyped(json, false);
}

export function PageResponseNumberItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseNumberItems {
    if (json == null) {
        return json;
    }
    return {
        
        'web': json['web'] == null ? undefined : json['web'],
        'android': json['android'] == null ? undefined : json['android'],
        'iOS': json['iOS'] == null ? undefined : json['iOS'],
    };
}

export function PageResponseNumberItemsToJSON(json: any): PageResponseNumberItems {
    return PageResponseNumberItemsToJSONTyped(json, false);
}

export function PageResponseNumberItemsToJSONTyped(value?: PageResponseNumberItems | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'web': value['web'],
        'android': value['android'],
        'iOS': value['iOS'],
    };
}

